package com.construction.platform.domain;

public enum AuditAction {
    ANNOTATION_CREATED,
    ANNOTATION_UPDATED,
    ANNOTATION_DELETED,
    ANNOTATION_ROLLBACK,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    DOCUMENT_UPLOADED,
    DOCUMENT_VERSION_SAVED,
    DOCUMENT_DELETED
}
